apiVersion: v1
kind: Secret
metadata:
  name: azcopy-sas-tokens
  namespace: default
  labels:
    app: docker-azcopy
type: Opaque
data:
  sas-origem: c2U9MjAyNS0wNy0xNlQxNCUzQTU5JTNBNTlaJnNwPXJsJnNwcj1odHRwcyZzdj0yMDI1LTA1LTA1JnNyPXMmc2lnPWF3amlGUGVwL0hpUnBhRXdGNmV3N25kRzFhTVVRVmJ6WmtRVTNuT01hVnMlM0Q=
  sas-destino: c2U9MjAyNS0wNy0xNlQxNSUzQTAxJTNBMDVaJnNwPXJjd2wmc3ByPWh0dHBzJnN2PTIwMjItMTEtMDImc3I9YyZzaWc9VnBuNUNoJTJCRTNTdjlqZXpKenN0QnVDanQlMkI3b3U5WnlPQU9HL0pTQWxxUE0lM0Q=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-azcopy-script
  namespace: default
  labels:
    app: docker-azcopy
data:
  azcopy.sh: |
    #!/bin/bash
    set -euo pipefail

    # Configurações
    SA_ORIGEM="stbanprdbrstest"
    SA_DESTINO="stbanprdbrs"
    FILESHARE_NAME="client1"
    BLOB_CONTAINER="client1"

    # SAS Tokens pré-definidos
    SAS_ORIGEM="${SAS_ORIGEM_TOKEN}"
    SAS_DESTINO="${SAS_DESTINO_TOKEN}"

    # Cores para output
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m'

    echo -e "${BLUE}[INFO]${NC} === Iniciando sincronização FileShare -> Blob ==="

    # Constrói URLs completas
    SOURCE_URL="https://${SA_ORIGEM}.file.core.windows.net/${FILESHARE_NAME}?${SAS_ORIGEM}"
    DEST_URL="https://${SA_DESTINO}.blob.core.windows.net/${BLOB_CONTAINER}?${SAS_DESTINO}"

    echo -e "${BLUE}[INFO]${NC} Executando comando AzCopy sync..."

    # Executa AzCopy com timeout de 30 minutos
    azcopy sync "$SOURCE_URL" "$DEST_URL" \
        --from-to=FileBlob \
        --recursive \
        --delete-destination=true \
        --skip-version-check

    EXIT_CODE=$?

    if [ $EXIT_CODE -eq 0 ]; then
        echo -e "${GREEN}[SUCCESS]${NC} Sincronização concluída com sucesso!"
    elif [ $EXIT_CODE -eq 124 ]; then
        echo -e "${RED}[ERROR]${NC} Timeout - Sincronização cancelada após 30 minutos"
        exit $EXIT_CODE
    else
        echo -e "${RED}[ERROR]${NC} Falha na sincronização (código: $EXIT_CODE)"
        exit $EXIT_CODE
    fi

---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: docker-azcopy-cronjob
  namespace: default
  labels:
    app: docker-azcopy
spec:
  schedule: "* * * * *"  # A cada minuto (mínimo possível no CronJob)
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  
  jobTemplate:
    spec:
      activeDeadlineSeconds: 7200  # 2 horas
      backoffLimit: 2
      
      template:
        metadata:
          labels:
            app: docker-azcopy
        spec:
          restartPolicy: Never
          
          containers:
          - name: docker-azcopy
            image: dfsrj/docker-azcopy:latest
            command: ["/bin/bash"]
            args: ["/scripts/azcopy.sh"]
           
            env:
            - name: SAS_ORIGEM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azcopy-sas-tokens
                  key: sas-origem
            - name: SAS_DESTINO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azcopy-sas-tokens
                  key: sas-destino
            
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "300m"
            
            volumeMounts:
            - name: script-volume
              mountPath: /scripts
              readOnly: true
          
          volumes:
          - name: script-volume
            configMap:
              name: docker-azcopy-script
              defaultMode: 0755
