apiVersion: v1
kind: Secret
metadata:
  name: azcopy-sas-tokens
  namespace: default
  labels:
    app: azcopy-sync
type: Opaque
data:
  sas-origem: c2U9MjAyNS0wNy0xNlQxNCUzQTU5JTNBNTlaJnNwPXJsJnNwcj1odHRwcyZzdj0yMDI1LTA1LTA1JnNyPXMmc2lnPWF3amlGUGVwL0hpUnBhRXdGNmV3N25kRzFhTVVRVmJ6WmtRVTNuT01hVnMlM0Q=
  sas-destino: c2U9MjAyNS0wNy0xNlQxNSUzQTAxJTNBMDVaJnNwPXJjd2wmc3ByPWh0dHBzJnN2PTIwMjItMTEtMDImc3I9YyZzaWc9VnBuNUNoJTJCRTNTdjlqZXpKenN0QnVDanQlMkI3b3U5WnlPQU9HL0pTQWxxUE0lM0Q=

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azcopy-sync-script
  namespace: default
  labels:
    app: azcopy-sync
data:
  azcopy.sh: |
    #!/bin/bash
    set -euo pipefail

    # Configurações
    SA_ORIGEM="stbanprdbrstest"
    SA_DESTINO="stbanprdbrs"
    FILESHARE_NAME="client1"
    BLOB_CONTAINER="client1"

    # SAS Tokens pré-definidos
    SAS_ORIGEM="${SAS_ORIGEM_TOKEN}"
    SAS_DESTINO="${SAS_DESTINO_TOKEN}"

    # Cores para output
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    BLUE='\033[0;34m'
    NC='\033[0m'

    echo -e "${BLUE}[INFO]${NC} === Iniciando sincronização FileShare -> Blob ==="

    # Constrói URLs completas
    SOURCE_URL="https://${SA_ORIGEM}.file.core.windows.net/${FILESHARE_NAME}?${SAS_ORIGEM}"
    DEST_URL="https://${SA_DESTINO}.blob.core.windows.net/${BLOB_CONTAINER}?${SAS_DESTINO}"

    echo -e "${BLUE}[INFO]${NC} Executando comando AzCopy sync..."

    # Executa AzCopy com timeout de 30 minutos
    azcopy sync "$SOURCE_URL" "$DEST_URL" \
        --from-to=FileBlob \
        --recursive \
        --put-md5 \
        --skip-version-check

    EXIT_CODE=$?

    if [ $EXIT_CODE -eq 0 ]; then
        echo -e "${GREEN}[SUCCESS]${NC} Sincronização concluída com sucesso!"
    elif [ $EXIT_CODE -eq 124 ]; then
        echo -e "${RED}[ERROR]${NC} Timeout - Sincronização cancelada após 30 minutos"
        exit $EXIT_CODE
    else
        echo -e "${RED}[ERROR]${NC} Falha na sincronização (código: $EXIT_CODE)"
        exit $EXIT_CODE
    fi

---
piVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "5"
    labels:
      app: docker-azcopy
    name: docker-azcopy-deployment
    namespace: default
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: docker-azcopy
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: docker-azcopy
      spec:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: agentpool
                  operator: In
                  values:
                  - npsystem
                  - tmpsystem
        containers:
        - args:
          - /scripts/azcopy.sh
          command:
          - /bin/bash
          env:
          - name: SAS_ORIGEM_TOKEN
            valueFrom:
              secretKeyRef:
                key: sas-origem
                name: azcopy-sas-tokens
          - name: SAS_DESTINO_TOKEN
            valueFrom:
              secretKeyRef:
                key: sas-destino
                name: azcopy-sas-tokens
          image: dfsrj/docker-azcopy:latest
          imagePullPolicy: Always
          name: docker-azcopy
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /scripts
            name: script-volume
            readOnly: true
        dnsPolicy: ClusterFirst
        nodeSelector:
          agentpool: npsystem
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: CriticalAddonsOnly
          operator: Exists
        volumes:
        - configMap:
            defaultMode: 493
            name: docker-azcopy-script
          name: script-volume
kind: List
metadata: {}