apiVersion: v1
kind: Secret
metadata:
  name: azcopy-sas-tokens
  namespace: default
type: Opaque
data:
  # SAS Tokens em Base64
  # Para atualizar os tokens, use:
  # echo "seu_token_aqui" | base64 -w 0
  
  # Token da origem (FileShare)
  sas-origem: c2U9MjAyNS0wNy0xNlQxNCUzQTU5JTNBNTlaJnNwPXJsJnNwcj1odHRwcyZzdj0yMDI1LTA1LTA1JnNyPXMmc2lnPWF3amlGUGVwL0hpUnBhRXdGNmV3N25kRzFhTVVRVmJ6WmtRVTNuT01hVnMlM0Q=
  
  # Token do destino (Blob Container)
  sas-destino: c2U9MjAyNS0wNy0xNlQxNSUzQTAxJTNBMDVaJnNwPXJjd2wmc3ByPWh0dHBzJnN2PTIwMjItMTEtMDImc3I9YyZzaWc9VnBuNUNoJTJCRTNTdjlqZXpKenN0QnVDanQlMkI3b3U5WnlPQU9HL0pTQWxxUE0lM0Q=

---
# Para gerar novos tokens em Base64:
# echo "se=2025-07-16T14%3A59%3A59Z&sp=rl&spr=https&sv=2025-05-05&sr=s&sig=awjiFPep/HiRpaEwF6ew7ndG1aMUQVbzZkQU3nOMaVs%3D" | base64 -w 0
# echo "se=2025-07-16T15%3A01%3A05Z&sp=rcwl&spr=https&sv=2022-11-02&sr=c&sig=Vpn5Ch%2BE3Sv9jezJzstBuCjt%2B7ou9ZyOAOG/JSAlqPM%3D" | base64 -w 0
